version: "3.9"

services:
  web-server:
    build: .
    command: 'php artisan serve --host=0.0.0.0'
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=remotemysql.com
      - DB_DATABASE=TwOuf3vrD9
      - DB_USERNAME=TwOuf3vrD9
      - DB_PASSWORD=FjGqvZAs6r